name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'web-server/**'
      - 'api-server/**'
  push:
    branches:
      - main
    paths:
      - 'web-server/**'
      - 'api-server/**'

jobs:

  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
        working-directory: ./${{ matrix.dir }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['web-server', 'api-server']
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install
    
    - name: 'Run Tests'
      run: npm run test

  lint:
    name: 'Run linter'
    defaults:
      run:
        shell: bash
        working-directory: ./${{ matrix.dir }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['web-server', 'api-server']
    steps:    
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    
    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run Linter'
      run: npx standard -v
