name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
      - developer
    paths:
      - 'web-server/**'
  push:
    branches:
      - main
      - developer
    paths:
      - 'web-server/**'
  workflow_dispatch:

jobs:

  test-web-server:
    name: 'Run unit tests for web-server'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install
      working-directory: ./web-server

    - name: Run Tests
      run: npm run test
      working-directory: ./web-server

  lint-web-server:
    name: 'Run linter and prettify for web-server'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install
      working-directory: ./web-server

    - name: Auto-fix linting issues and prettify
      run: npm run lint -- --fix && npm run prettify -- --write
      working-directory: ./web-server

    - name: Run Linter
      run: npm run lint
      working-directory: ./web-server
