name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
      - developer
    paths:
      - 'web-server/**'
      - 'api-server/**'
  push:
    branches:
      - main
      - developer
    paths:
      - 'web-server/**'
      - 'api-server/**'
  workflow_dispatch:

jobs:

  test-web-server:
    name: 'Run unit tests for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Run Tests
        run: npm run test
        working-directory: ./web-server

  lint-web-server:
    name: 'Lint code for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Auto-fix linting issues
        run: npm run lint -- --fix
        working-directory: ./web-server

      - name: Run Linter
        run: npm run lint
        working-directory: ./web-server

  prettify-web-server:
    name: 'Prettify code for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # This will checkout the branch of the pull request
          fetch-depth: 0 # This will ensure all history is fetched

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Prettify code
        run: npm run prettify
        working-directory: ./web-server

      - name: Commit and push changes
        run: |
          git config --global user.name 'carlpm'
          git config --global user.email 'carlpm@stud.ntnu.no'
          git add -A
          git diff --staged --quiet || git commit -m "Prettify JS code"
          git push origin prettify-${{ github.head_ref }} --set-upstream
        working-directory: ./web-server
      

  test-api-server:
    name: 'Run unit tests for api-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./api-server

      - name: Run Tests
        run: npm run test
        working-directory: ./api-server

  lint-api-server:
    name: 'Lint code for api-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./api-server

      - name: Auto-fix linting issues
        run: npm run lint -- --fix
        working-directory: ./api-server

      - name: Run Linter
        run: npm run lint
        working-directory: ./api-server

  prettify-api-server:
    name: 'Prettify code for api-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./api-server

      - name: Prettify code
        run: npm run prettify
        working-directory: ./api-server
