name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
      - developer
    paths:
      - 'web-server/**'
      # - 'api-server/**' # Commented out to exclude 'api-server' changes from the workflow
  push:
    branches:
      - main
      - developer
    paths:
      - 'web-server/**'
      # - 'api-server/**' # Commented out to exclude 'api-server' changes from the workflow
  workflow_dispatch:

jobs:

  test-web-server:
    name: 'Run unit tests for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Run Tests
        run: npm run test
        working-directory: ./web-server

  lint-web-server:
    name: 'Lint code for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Auto-fix linting issues
        run: npm run lint -- --fix
        working-directory: ./web-server

      - name: Run Linter
        run: npm run lint
        working-directory: ./web-server

  prettify-web-server:
    name: 'Prettify code for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use v2 for better compatibility
        with:
          ref: main
          fetch-depth: 0  # Fetch the full history to allow pushing changes

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Prettify code
        run: npm run prettify
        working-directory: ./web-server

      - name: Set Git user identity
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
        shell: bash

      - name: Commit changes
        run: |
          git add -A
          git diff --staged --quiet || git commit -m "Prettify JS code"
        working-directory: ./web-server

      - name: Push changes to main branch
        run: git push origin HEAD:main
        working-directory: ./web-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Commented out the 'api-server' related jobs
