name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
      - developer
    paths:
      - 'web-server/**'
      # - 'api-server/**' # Commented out to exclude 'api-server' changes from the workflow
  push:
    branches:
      - main
      - developer
    paths:
      - 'web-server/**'
      # - 'api-server/**' # Commented out to exclude 'api-server' changes from the workflow
  workflow_dispatch:

jobs:

  test-web-server:
    name: 'Run unit tests for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Run Tests
        run: npm run test
        working-directory: ./web-server

  lint-web-server:
    name: 'Lint code for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Auto-fix linting issues
        run: npm run lint -- --fix
        working-directory: ./web-server

      - name: Run Linter
        run: npm run lint
        working-directory: ./web-server
        
  prettify-web-server:
    name: 'Prettify code for web-server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all branches and tags are fetched

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-server

      - name: Prettify code
        run: npm run prettify
        working-directory: ./web-server

      - name: Check if there are changes
        id: git-check
        run: |
          git diff --exit-code || echo "::set-output name=changed::true"
        working-directory: ./web-server

      - name: Commit changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Apply Prettier formatting"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./web-server



# Commented out the 'api-server' related jobs
