name: Update Server

on:
  push:
    branches:
      - main  # or your branch name
      - developer # or your branch name
jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Server
      run: |
        # Run the update script on your server via SSH
        ssh ubuntu@129.241.150.249 'bash -s' < update.sh
