name: Update Server

on:
  push:
    branches:
      - main  # or your branch name
      - developer

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Server
      run: |
        # Run the update script on your server via SSH
        ssh user@your-server-ip 'bash -s' < update.sh
