name: Update Server

on:
  push:
    branches:
      - main  # or your branch name
      - developer # or your branch name
  workflow_dispatch:  # This enables manual triggering of the workflow

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 129.241.150.249 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Update Server
      run: |
        # Run the update script on your server via SSH
        ssh ubuntu@129.241.150.249 'bash -s' < Interactive-Database-for-Environmental-Data-Test/scripts/update.sh
